# Generated by Django 2.0.1 on 2018-07-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookuser',
            name='age',
            field=models.PositiveIntegerField(null=True, verbose_name='Возраст пользователя'),
        ),
    ]
